# Plagiarism Detection Model

Now that you've created training and test data, you are ready to define and train a model. Your goal in this notebook, will be to train a binary classification model that learns to label an answer file as either plagiarized or not, based on the features you provide the model.

This task will be broken down into a few discrete steps:

* Upload your data to S3.
* Define a binary classification model and a training script.
* Train your model and deploy it.
* Evaluate your deployed classifier and answer some questions about your approach.

To complete this notebook, you'll have to complete all given exercises and answer all the questions in this notebook.
> All your tasks will be clearly labeled **EXERCISE** and questions as **QUESTION**.

It will be up to you to explore different classification models and decide on a model that gives you the best performance for this dataset.

---

## Load Data to S3

In the last notebook, you should have created two files: a `training.csv` and `test.csv` file with the features and class labels for the given corpus of plagiarized/non-plagiarized text data. 

>The below cells load in some AWS SageMaker libraries and creates a default bucket. After creating this bucket, you can upload your locally stored data to S3.

Save your train and test `.csv` feature files, locally. To do this you can run the second notebook "2_Plagiarism_Feature_Engineering" in SageMaker or you can manually upload your files to this notebook using the upload icon in Jupyter Lab. Then you can upload local files to S3 by using `sagemaker_session.upload_data` and pointing directly to where the training data is saved.

In [1]:
import pandas as pd
import boto3
import sagemaker

In [22]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# session and role
sagemaker_session = sagemaker.Session()
role = sagemaker.get_execution_role()

# create an S3 bucket
bucket = sagemaker_session.default_bucket()

## EXERCISE: Upload your training data to S3

Specify the `data_dir` where you've saved your `train.csv` file. Decide on a descriptive `prefix` that defines where your data will be uploaded in the default S3 bucket. Finally, create a pointer to your training data by calling `sagemaker_session.upload_data` and passing in the required parameters. It may help to look at the [Session documentation](https://sagemaker.readthedocs.io/en/stable/session.html#sagemaker.session.Session.upload_data) or previous SageMaker code examples.

You are expected to upload your entire directory. Later, the training script will only access the `train.csv` file.

In [23]:
# should be the name of directory you created to save your features data
data_dir = 'plagiarism_data'

# set prefix, a descriptive name for a directory  
prefix = 'training_data'

# upload all data to S3
input_data = sagemaker_session.upload_data(path=data_dir, bucket=bucket, key_prefix=prefix)
print(input_data)

s3://sagemaker-us-east-1-268876635163/training_data


### Test cell

Test that your data has been successfully uploaded. The below cell prints out the items in your S3 bucket and will throw an error if it is empty. You should see the contents of your `data_dir` and perhaps some checkpoints. If you see any other files listed, then you may have some old model files that you can delete via the S3 console (though, additional files shouldn't affect the performance of model developed in this notebook).

In [24]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# confirm that data is in S3 bucket
empty_check = []
for obj in boto3.resource('s3').Bucket(bucket).objects.all():
    empty_check.append(obj.key)
    print(obj.key)

assert len(empty_check) !=0, 'S3 bucket is empty.'
print('Test passed!')

sagemaker-pytorch-2021-01-05-08-24-20-307/debug-output/training_job_end.ts
sagemaker-pytorch-2021-01-05-08-24-20-307/output/model.tar.gz
sagemaker-pytorch-2021-01-05-08-24-20-307/source/sourcedir.tar.gz
sagemaker-pytorch-2021-01-05-09-33-28-511/debug-output/training_job_end.ts
sagemaker-pytorch-2021-01-05-09-33-28-511/output/model.tar.gz
sagemaker-pytorch-2021-01-05-09-33-28-511/source/sourcedir.tar.gz
sagemaker-pytorch-2021-01-05-14-45-35-684/debug-output/training_job_end.ts
sagemaker-pytorch-2021-01-05-14-45-35-684/output/model.tar.gz
sagemaker-pytorch-2021-01-05-14-45-35-684/source/sourcedir.tar.gz
sagemaker-pytorch-2021-01-05-21-45-42-708/sourcedir.tar.gz
sagemaker-pytorch-2021-01-05-21-57-45-220/sourcedir.tar.gz
sagemaker-pytorch-2021-01-05-23-35-17-190/debug-output/training_job_end.ts
sagemaker-pytorch-2021-01-05-23-35-17-190/output/model.tar.gz
sagemaker-pytorch-2021-01-05-23-35-17-190/source/sourcedir.tar.gz
sagemaker-pytorch-2021-01-06-13-42-30-265/debug-output/training_job_en

---

# Modeling

Now that you've uploaded your training data, it's time to define and train a model!

The type of model you create is up to you. For a binary classification task, you can choose to go one of three routes:
* Use a built-in classification algorithm, like LinearLearner.
* Define a custom Scikit-learn classifier, a comparison of models can be found [here](https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html).
* Define a custom PyTorch neural network classifier. 

It will be up to you to test out a variety of models and choose the best one. Your project will be graded on the accuracy of your final model. 
 
---

## EXERCISE: Complete a training script 

To implement a custom classifier, you'll need to complete a `train.py` script. You've been given the folders `source_sklearn` and `source_pytorch` which hold starting code for a custom Scikit-learn model and a PyTorch model, respectively. Each directory has a `train.py` training script. To complete this project **you only need to complete one of these scripts**; the script that is responsible for training your final model.

A typical training script:
* Loads training data from a specified directory
* Parses any training & model hyperparameters (ex. nodes in a neural network, training epochs, etc.)
* Instantiates a model of your design, with any specified hyperparams
* Trains that model 
* Finally, saves the model so that it can be hosted/deployed, later

### Defining and training a model
Much of the training script code is provided for you. Almost all of your work will be done in the `if __name__ == '__main__':` section. To complete a `train.py` file, you will:
1. Import any extra libraries you need
2. Define any additional model training hyperparameters using `parser.add_argument`
2. Define a model in the `if __name__ == '__main__':` section
3. Train the model in that same section

Below, you can use `!pygmentize` to display an existing `train.py` file. Read through the code; all of your tasks are marked with `TODO` comments. 

**Note: If you choose to create a custom PyTorch model, you will be responsible for defining the model in the `model.py` file,** and a `predict.py` file is provided. If you choose to use Scikit-learn, you only need a `train.py` file; you may import a classifier from the `sklearn` library.

In [25]:
# directory can be changed to: source_sklearn or source_pytorch
!pygmentize source_pytorch/train.py

import argparse
import json
import os
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import torch.utils.data

# imports the model in model.py by name
from model import BinaryClassifier

def model_fn(model_dir):
    """Load the PyTorch model from the `model_dir` directory."""
    print("Loading model.")

    # First, load the parameters used to create the model.
    model_info = {}
    model_info_path = os.path.join(model_dir, 'model_info.pth')
    with open(model_info_path, 'rb') as f:
        model_info = torch.load(f)

    print("model_info: {}".format(model_info))

    # Determine the device and construct the model.
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = BinaryClassifier(model_info['input_features'], model_info['hidden_dim'], model_info['output_dim']).double()

    # Load the stored model parameters.
    model_path = os.path.join(model_dir, 'model.pth')
    with open(model_path, 'rb') as f:
        mo

### Provided code

If you read the code above, you can see that the starter code includes a few things:
* Model loading (`model_fn`) and saving code
* Getting SageMaker's default hyperparameters
* Loading the training data by name, `train.csv` and extracting the features and labels, `train_x`, and `train_y`

If you'd like to read more about model saving with [joblib for sklearn](https://scikit-learn.org/stable/modules/model_persistence.html) or with [torch.save](https://pytorch.org/tutorials/beginner/saving_loading_models.html), click on the provided links.

---
# Create an Estimator

When a custom model is constructed in SageMaker, an entry point must be specified. This is the Python file which will be executed when the model is trained; the `train.py` function you specified above. To run a custom training script in SageMaker, construct an estimator, and fill in the appropriate constructor arguments:

* **entry_point**: The path to the Python script SageMaker runs for training and prediction.
* **source_dir**: The path to the training script directory `source_sklearn` OR `source_pytorch`.
* **entry_point**: The path to the Python script SageMaker runs for training and prediction.
* **source_dir**: The path to the training script directory `train_sklearn` OR `train_pytorch`.
* **entry_point**: The path to the Python script SageMaker runs for training.
* **source_dir**: The path to the training script directory `train_sklearn` OR `train_pytorch`.
* **role**: Role ARN, which was specified, above.
* **train_instance_count**: The number of training instances (should be left at 1).
* **train_instance_type**: The type of SageMaker instance for training. Note: Because Scikit-learn does not natively support GPU training, Sagemaker Scikit-learn does not currently support training on GPU instance types.
* **sagemaker_session**: The session used to train on Sagemaker.
* **hyperparameters** (optional): A dictionary `{'name':value, ..}` passed to the train function as hyperparameters.

Note: For a PyTorch model, there is another optional argument **framework_version**, which you can set to the latest version of PyTorch, `1.0`.

## EXERCISE: Define a Scikit-learn or PyTorch estimator

To import your desired estimator, use one of the following lines:
```
from sagemaker.sklearn.estimator import SKLearn
```
```
from sagemaker.pytorch import PyTorch
```

In [26]:

# your import and estimator code, here
# import a PyTorch wrapper
from sagemaker.pytorch import PyTorch

# specify an output path
# prefix is specified above
output_path = 's3://{}/{}'.format(bucket, prefix)

# instantiate a pytorch estimator
estimator = PyTorch(entry_point='train.py',
                    source_dir='source_pytorch', # pytorch
                    role=role,
                    framework_version='1.0',
                    py_version = 'py3',
                    train_instance_count=1,
                    train_instance_type='ml.m4.xlarge',
                    output_path=output_path,
                    sagemaker_session=sagemaker_session,
                    hyperparameters={
                        'input_features': 3,  # num of features
                        'hidden_dim': 30,
                        'output_dim': 1,
                        'epochs': 180 # could change to higher
                    })

train_instance_count has been renamed in sagemaker>=2.
See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.
train_instance_type has been renamed in sagemaker>=2.
See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.


## EXERCISE: Train the estimator

Train your estimator on the training data stored in S3. This should create a training job that you can monitor in your SageMaker console.

In [27]:
%%time

# Train your estimator on S3 training data
estimator.fit({'train': input_data})


2021-03-01 23:49:17 Starting - Starting the training job...
2021-03-01 23:49:41 Starting - Launching requested ML instancesProfilerReport-1614642557: InProgress
......
2021-03-01 23:50:41 Starting - Preparing the instances for training......
2021-03-01 23:51:42 Downloading - Downloading input data......
2021-03-01 23:52:43 Training - Downloading the training image...
2021-03-01 23:53:13 Uploading - Uploading generated training modelbash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2021-03-01 23:53:04,887 sagemaker-containers INFO     Imported framework sagemaker_pytorch_container.training
2021-03-01 23:53:04,891 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)
2021-03-01 23:53:04,914 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2021-03-01 23:53:05,534 sagemaker_pytorch_container.training INFO     Invoking user training script.
2021-03-01 23:53:05,865 sage

## EXERCISE: Deploy the trained model

After training, deploy your model to create a `predictor`. If you're using a PyTorch model, you'll need to create a trained `PyTorchModel` that accepts the trained `<model>.model_data` as an input parameter and points to the provided `source_pytorch/predict.py` file as an entry point. 

To deploy a trained model, you'll use `<model>.deploy`, which takes in two arguments:
* **initial_instance_count**: The number of deployed instances (1).
* **instance_type**: The type of SageMaker instance for deployment.

Note: If you run into an instance error, it may be because you chose the wrong training or deployment instance_type. It may help to refer to your previous exercise code to see which types of instances we used.

In [28]:
%%time

# uncomment, if needed
from sagemaker.pytorch import PyTorchModel


# Create a model from the trained estimator data
# And point to the prediction script
model = PyTorchModel(model_data=estimator.model_data,
                     role = role,
                     framework_version='1.0',
                     py_version = 'py3',
                     entry_point='predict.py',
                     source_dir='source_pytorch')

# deploy your model to create a predictor
predictor = estimator.deploy(initial_instance_count=1, instance_type='ml.m4.xlarge')


---------------!CPU times: user 291 ms, sys: 6.84 ms, total: 297 ms
Wall time: 7min 32s


---
# Evaluating Your Model

Once your model is deployed, you can see how it performs when applied to our test data.

The provided cell below, reads in the test data, assuming it is stored locally in `data_dir` and named `test.csv`. The labels and features are extracted from the `.csv` file.

In [29]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
import os

# read in test data, assuming it is stored locally
test_data = pd.read_csv(os.path.join(data_dir, "test.csv"), header=None, names=None)

# labels are in the first column
test_y = test_data.iloc[:,0]
test_x = test_data.iloc[:,1:]

## EXERCISE: Determine the accuracy of your model

Use your deployed `predictor` to generate predicted, class labels for the test data. Compare those to the *true* labels, `test_y`, and calculate the accuracy as a value between 0 and 1.0 that indicates the fraction of test data that your model classified correctly. You may use [sklearn.metrics](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics) for this calculation.

**To pass this project, your model should get at least 90% test accuracy.**

In [30]:
# First: generate predicted, class labels
test_y_preds = predictor.predict(test_x.values)


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# test that your model generates the correct number of labels
assert len(test_y_preds)==len(test_y), 'Unexpected number of predictions.'
print('Test passed!')

Test passed!


In [56]:
# Second: calculate the test accuracy
# calculate true positives, false positives, true negatives, false negatives
import numpy as np 
import pandas as pd 
class_col = []
for value in test_y_preds:
    if value >= 0.5:
        class_col.append(1)
    if value < 0.5:
        class_col.append(0)
    if value == -1:
        class_col.append(-1)

converted = np.array(class_col)
print(test_x.values)
print(converted)

tp = np.logical_and(test_y.values, converted).sum()
fp = np.logical_and(1-test_y.values, converted).sum()
tn = np.logical_and(1-test_y.values, 1-converted).sum()
fn = np.logical_and(test_y.values, 1-converted).sum()

# calculate binary classification metrics
recall = tp / (tp + fn)
precision = tp / (tp + fp)
accuracy = (tp + tn) / (tp + fp + tn + fn)

# printing a table of metrics
print("\n{:<11} {:.3f}".format('Recall:', recall))
print("{:<11} {:.3f}".format('Precision:', precision))
print("{:<11} {:.3f}".format('Accuracy:', accuracy))
print("\n{:<11} {:.3f}".format('False negatives:', fn))
print("{:<11} {:.3f}".format('False positives:', fp))
print("{:<11} {:.3f}".format('True negatives:', tn))
print("{:<11} {:.3f}".format('True positives:', tp))

## print out the array of predicted and true labels, if you want
print('\nPredicted class labels: ')
print(test_y_preds)
print('\nTrue class labels: ')
print(test_y.values)

[[1.         0.92227979 0.82075472]
 [0.76530612 0.58965517 0.62171053]
 [0.88444444 0.18099548 0.59745763]
 [0.61904762 0.04324324 0.42783505]
 [0.92       0.3943662  0.775     ]
 [0.99267399 0.9739777  0.99305556]
 [0.41269841 0.         0.34666667]
 [0.46268657 0.         0.18932039]
 [0.58115183 0.         0.24742268]
 [0.58421053 0.         0.29441624]
 [0.56637168 0.         0.25833333]
 [0.48148148 0.02290076 0.27891156]
 [0.61979167 0.02659574 0.34158416]
 [0.92173913 0.65486726 0.92941176]
 [1.         0.92248062 1.        ]
 [0.86153846 0.06282723 0.50471698]
 [0.62616822 0.22397476 0.55855856]
 [1.         0.9688716  0.99669967]
 [0.38383838 0.01030928 0.17874396]
 [1.         0.94464945 0.85467128]
 [0.61392405 0.         0.29834254]
 [0.97276265 0.83003953 0.92708333]
 [0.96280992 0.68907563 0.90980392]
 [0.41525424 0.         0.17741935]
 [0.53218884 0.01746725 0.24583333]]
[1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 0]
25

Recall:     1.000
Precision:  1.000
Accurac

### Question 1: How many false positives and false negatives did your model produce, if any? And why do you think this is?

** Answer**: The model produced no false positives and no false negatives. Because the model used a hidden layer with the dimension of 30 and also the Dropout rate of output layer is low: 0.1, so that the abnormalies are strictly eliminated.

### Question 2: How did you decide on the type of model to use? 

** Answer**: The pytorch model is provided during the training and I wanted first implement it correctly, before moving to scikitlearn. Also the foundation created for pytorch model during training is really good and easy to implement ideas, so I decided to use it.



----
## EXERCISE: Clean up Resources

After you're done evaluating your model, **delete your model endpoint**. You can do this with a call to `.delete_endpoint()`. You need to show, in this notebook, that the endpoint was deleted. Any other resources, you may delete from the AWS console, and you will find more instructions on cleaning up all your resources, below.

In [58]:
# uncomment and fill in the line below!
predictor.delete_endpoint()


### Deleting S3 bucket

When you are *completely* done with training and testing models, you can also delete your entire S3 bucket. If you do this before you are done training your model, you'll have to recreate your S3 bucket and upload your training data again.

In [59]:
# deleting bucket, uncomment lines below

bucket_to_delete = boto3.resource('s3').Bucket(bucket)
bucket_to_delete.objects.all().delete()

[{'ResponseMetadata': {'RequestId': '7B7Q4F3RMB1Z2NW0',
   'HostId': 'JWfu42baeCuSaK/w4i5AsCY2ipGttvPLzQ1nhOxP+cnPs80JiwJJAIMWhnqjfqKaU03pHgY03+s=',
   'HTTPStatusCode': 200,
   'HTTPHeaders': {'x-amz-id-2': 'JWfu42baeCuSaK/w4i5AsCY2ipGttvPLzQ1nhOxP+cnPs80JiwJJAIMWhnqjfqKaU03pHgY03+s=',
    'x-amz-request-id': '7B7Q4F3RMB1Z2NW0',
    'date': 'Tue, 02 Mar 2021 00:32:44 GMT',
    'content-type': 'application/xml',
    'transfer-encoding': 'chunked',
    'server': 'AmazonS3',
    'connection': 'close'},
   'RetryAttempts': 0},
  'Deleted': [{'Key': 'training_data/sagemaker-pytorch-2021-03-01-23-13-38-738/rule-output/ProfilerReport-1614640418/profiler-output/profiler-reports/IOBottleneck.json'},
   {'Key': 'sagemaker-pytorch-2021-02-28-08-34-41-406/source/sourcedir.tar.gz'},
   {'Key': 'training_data/sagemaker-pytorch-2021-02-28-10-10-22-198/rule-output/ProfilerReport-1614507022/profiler-output/profiler-report.html'},
   {'Key': 'training_data/sagemaker-pytorch-2021-02-28-19-26-46-712/rule

### Deleting all your models and instances

When you are _completely_ done with this project and do **not** ever want to revisit this notebook, you can choose to delete all of your SageMaker notebook instances and models by following [these instructions](https://docs.aws.amazon.com/sagemaker/latest/dg/ex1-cleanup.html). Before you delete this notebook instance, I recommend at least downloading a copy and saving it, locally.

---
## Further Directions

There are many ways to improve or add on to this project to expand your learning or make this more of a unique project for you. A few ideas are listed below:
* Train a classifier to predict the *category* (1-3) of plagiarism and not just plagiarized (1) or not (0).
* Utilize a different and larger dataset to see if this model can be extended to other types of plagiarism.
* Use language or character-level analysis to find different (and more) similarity features.
* Write a complete pipeline function that accepts a source text and submitted text file, and classifies the submitted text as plagiarized or not.
* Use API Gateway and a lambda function to deploy your model to a web application.

These are all just options for extending your work. If you've completed all the exercises in this notebook, you've completed a real-world application, and can proceed to submit your project. Great job!